version: "3.7"

services:
  # Обязательный системный прокси для интеграции в интерфейс Umbrel
  app_proxy:
    image: getumbrel/app-proxy:v0.1.1
    environment:
      APP_HOST: steam_app_1      # Имя контейнера внутри сети Docker (собирается как <имя_папки>_<имя_сервиса>_1)
      APP_PORT: 3001             # Направляем трафик на HTTPS порт Selkies
      PROXY_TYPE: "https"        # КРИТИЧЕСКИ ВАЖНО: заставляет прокси общаться с контейнером по HTTPS
      PROXY_AUTH_ADD: "false"    # Отключает базовую авторизацию Umbrel, так как у Steam своя сессия

  app:
    image: lscr.io/linuxserver/steam:latest
    container_name: steam
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - LC_ALL=ru_RU.UTF-8
      - AUTO_GPU=true
      - SELKIES_ENCODER=x264enc
    volumes:
      - $APP_DATA_DIR/config:/config
    ports:
      # Пробрасываем системную переменную порта. Umbrel сам назначит сюда 3006
      - $APP_PORT:80
    shm_size: "2gb"
    restart: on-failure
